# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy necessary files
COPY app.py requirements.txt ./
COPY uploads ./uploads

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose port
EXPOSE 5001

# Run the application
CMD ["python", "app.py"]
