# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy files
COPY backend/package.json backend/package-lock.json ./
COPY backend/index.js ./
COPY backend/uploads ./uploads

# Install dependencies
RUN npm install

# Expose port
EXPOSE 5002

# Run the server
CMD ["node", "index.js"]
